# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
palette:
  blue: "#8AADF4"
  closer: p:os
  lavender: "#B7BDF8"
  os: "#ACB0BE"
  pink: "#F5BDE6"
  maroon: "#e64553"
upgrade:
  source: cdn
  interval: 168h
  auto: false
  notice: false
transient_prompt:
  background: transparent
  foreground: "#ffffff"
  template: " "
blocks:
- type: prompt
  alignment: left
  segments:
  - template: "{{.Icon}} "
    foreground: p:os
    type: os
    style: plain
  - properties:
      style: agnoster_short
    template: "{{ .Path }} "
    foreground: p:pink
    type: path
    style: plain
    max_depth: 2
  - properties:
      branch_icon: "\ue725 "
      cherry_pick_icon: "\ue29b "
      commit_icon: "\uf417 "
      fetch_status: false
      fetch_upstream_icon: false
      merge_icon: "\ue727 "
      no_commits_icon: "\uf0c3 "
      rebase_icon: "\ue728 "
      revert_icon: "\uf0e2 "
      tag_icon: "\uf412 "
    template: "{{ .HEAD }} "
    foreground: p:lavender
    type: git
    style: plain
  - type: kubectl
    style: plain
    foreground: p:maroon
    template: " ﴱ {{.Cluster}}{{if .Namespace}} :: {{.Namespace}}{{end}} "
    properties:
      context_aliases:
        test01-connect/api-kafka04t-sbb-aws-test-net:6443/u238748: kafka04t
- type: prompt
  alignment: left
  newline: true
  segments:
  - template: 
    foreground: p:closer
    type: text
    style: plain
    newline: true
version: 3
final_space: true
