terminal_background = 'p:t-background'
console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'
version = 3
final_space = true

[palette]
  blue-bell = '#9aa5ce'
  blue-black = '#565f89'
  celeste-blue = '#b4f9f8'
  light-sky-blue = '#7dcfff'
  main-bg = '#24283b'
  pastal-grey = '#cfc9c2'
  pistachio-green = '#9ece6a'
  t-background = 'p:main-bg'
  terminal-black = '#414868'
  terminal-blue = '#7aa2f7'
  terminal-green = '#73daca'
  terminal-magenta = '#bb9af7'
  terminal-purple = '#9d7cd8'
  terminal-red = '#f7768e'
  terminal-white = '#c0caf5'
  terminal-yellow = '#e0af68'
  white-blue = '#a9b1d6'

[secondary_prompt]
  template = '➜ '
  foreground = 'p:terminal-blue'
  background = 'transparent'

[transient_prompt]
  template = '➜ '
  foreground = 'p:terminal-blue'
  background = 'p:t-background'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = ' '
    foreground = 'p:white'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .Path }} <p:light-sky-blue></>'
    foreground = '#8aadf4'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'mixed'

  [[blocks.segments]]
    template = '󱃾 <b>{{ .Context }}{{ if .Namespace }}::{{ .Namespace }}{{ end }}</b>'
    foreground = '#f5bde6'
    type = 'kubectl'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    foreground = '#a6da95'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = '   '
      cache_duration = 'none'
      fetch_status = true

  [[blocks.segments]]
    template = ' '
    foreground = 'p:terminal-red'
    type = 'status'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    template = ' {{ .Full}}'
    foreground = 'p:light-sky-blue'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = '#e25928'
    type = 'rust'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    foreground = 'p:white-blue'
    type = 'command'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      command = 'echo $TICKET'
      shell = 'zsh'

  [[blocks.segments]]
    foreground = 'p:white-blue'
    type = 'command'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      command = 'git log --pretty=format:%cr -1 || date +%H:%M:%S'
      shell = 'bash'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '➜'
    foreground = 'p:pistachio-green'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
